spring.jpa.hibernate.ddl-auto=${DB_DDL_AUTO:create-drop}
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3307/sistema-asistencia?useSSL=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
logging.level.org.hibernate.SQL=error

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT Configuration
jwt.secret.key=${JWT_SECRET_KEY}
jwt.expiration.time=${JWT_EXPIRATION_TIME:86400000}
jwt.refresh.expiration.time=${JWT_REFRESH_EXPIRATION_TIME:604800000}

# Configuración de Redis actualizada
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}


